[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = true
port = 8501
enableXsrfProtection = false

[logger]
level = "error"

[client]
toolbarMode = "minimal"
showErrorDetails = true
